name: 'bugsnag-dsym-upload tests'

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3']
        os: [ubuntu-24.04, macos-13]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: install dependencies (Ubuntu only)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y llvm
        sudo ln -s $(which llvm-dwarfdump) $(dirname $(which llvm-dwarfdump))/dwarfdump

    - run: mkdir -p vendor/{fastlane-bundle,bundle}

    - name: run specs
      run: |
        curl -o- https://raw.githubusercontent.com/bugsnag/bugsnag-cli/main/install.sh | bash
        bundle config path vendor/fastlane-bundle
        bundle install --gemfile=tools/fastlane-plugin/Gemfile
        cd tools/fastlane-plugin
        bundle exec rspec

    - name: run MazeRunner (macOS only)
      if: contains(matrix.os, 'macos')
      run: |
        bundle config path vendor/bundle
        bundle install --gemfile=Gemfile
        bundle exec maze-runner features/*.feature
