default_platform(:ios)

endpoint = ENV['BUGSNAG_ENDPOINT']
api_key = ENV['BUGSNAG_API_KEY']
config_file = ENV['BUGSNAG_CONFIG_FILE']

platform :ios do
  lane :send_build do
    send_build_to_bugsnag(upload_url: endpoint, api_key: api_key)
  end

  lane :upload_symbols do
    if config_file.nil?
      upload_symbols_to_bugsnag(upload_url: endpoint)
    else
      upload_symbols_to_bugsnag(upload_url: endpoint, config_file: config_file)
    end
  end

  lane :upload_symbols_with_api_key do
    upload_symbols_to_bugsnag(upload_url: endpoint, api_key: api_key)
  end
end


